### ISSUE TITLE
Stats by Filter - Incorrect Sort

### ISSUE THREAD

**Issue by JonathanMaccollum** [alexhelms/lumidex#57]
**Describe the bug**
The table showing total hours and count by filter has a sort feature, but the sorting is alphabetical instead of numerical based:

**To Reproduce**
* Load a library containing data with more than one filter
* Search your library to produce a result set containing at least two unique filters
* Look at the Stats by Fitler table on the right
* Hit the column header "Total (hr)" or "Count" and notice the sorting occurs alphabetically instead of based on the numerical sum of hours or count.

**Expected behavior**
The sort should show the results with the most total integration time above the ones with less integration time when sorting by Total (hr)
The sort should show the results with the most number of files above the ones with fewer number of files when sorting by Count.

**Screenshots**
![image](https://github.com/user-attachments/assets/3363b771-7e97-43cf-96f3-5a597c9c0e03)

**Desktop (please complete the following information):**
 - OS: Windows 2022
 - Version 1.2.1

**Additional context**
na

**Comment by alexhelms** [comment]
Ah, the classic sorting bug. Thanks for finding this. I'll get this fixed for the next release.
