### ISSUE TITLE
Persistent filters after shutdown and re-opening

### ISSUE THREAD

**Issue by seanmakin** [alexhelms/lumidex#91]
**Is your feature request related to a problem? Please describe.**
99% of the time, when using Lumidex and selecting filters, I will default to the same filters with Image Type to "Light" and Image Kind to "Raw" as I'm checking the status of acquisition on a project.

![Screenshot 2024-12-11 211116](https://github.com/user-attachments/assets/f7abae6f-9173-440e-92d3-564cef603487)

**Describe the solution you'd like**
Add the ability to have persistent filters even after the program closes and re-opening so as to not constantly reselect the same filter attributes. Potentially make this optional if some users do not want this?

**Comment by alexhelms** [comment]
Thank you for the suggestion, that is a great idea. As you also suggested I agree that this feature be optional is probably the right call.

What do you think about an application setting named "Persist search filters on exit"?

**Comment by seanmakin** [comment]
Sounds like a great way to implement it!
